
language: shell
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
services:
  - docker
jobs:
  include:
  - name: build tag latest
    os: linux
    env: TAG=latest
    script: docker build --pull --tag mondedie/rutorrent:${TAG} .
  - name: build tag filebot
    os: linux
    env: TAG=filebot
    script: docker build --build-arg FILEBOT=true --pull --tag mondedie/rutorrent:${TAG} .

before_deploy:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

deploy:
  provider: script
  script: docker push mondedie/rutorrent:${TAG}
  branch: master
