os: linux
language: shell

arch: 
 - amd64
 - arm64

services:
  - docker

jobs:
  include:
  - name: build tag latest
    env: TAG=latest
    script: docker build --pull --tag mondedie/rutorrent:${TAG} .
  - name: build tag filebot
    env: TAG=filebot
    script: docker build --platform linux/${TRAVIS_CPU_ARCH} --build-arg FILEBOT=true --pull --tag mondedie/rutorrent:${TAG} .

before_deploy:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

deploy:
  provider: script
  script: docker push mondedie/rutorrent:${TAG}
  branch: master
